backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)


site_url: https://theramenpack.netlify.com

logo_url: https://theramenpack.netlify.com/images/logo.png

media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "static/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "/contents/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{day}}-{{month}}-{{year}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Rating (scale of 1-5)", name: "rating", widget: "number"}
      - {label: "Body", name: "body", widget: "markdown"}

# backend:
#   name: github
#   repo: isaaclipse/the-ramen-pack-web
#
# site_url: https://theramenpack.netlify.com
#
# publish_mode: editorial_workflow
#
# media_folder: static/uploads/images
# public_folder: /uploads/
#
# site_url: theramenpack.netlify.com
#
# logo_url: https://theramenpack.netlify.com/images/logo.png
#
# collections:
#   - label: "Post"
#     name: "post"
#     folder: "./contents/blog"
#     create: true
#     fields:
#       - { name: path, label: Path }
#       - { name: date, label: Date, widget: datetime }
#       - { name: title, label: Title }
#       - { name: body, label: Body, widget: markdown }
