backend:
  name: github
  repo: isaaclipse/the-ramen-pack-web

site_url: https://theramenpack.netlify.com

publish_mode: editorial_workflow

media_folder: static/uploads/images
public_folder: /uploads/

site_url: theramenpack.netlify.com

logo_url: https://theramenpack.netlify.com/images/logo.png

collections:
  - label: "Post"
    name: "post"
    folder: "./contents/blog"
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
